In [1]:
python

NameError: name 'python' is not defined

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame({

_IncompleteInputError: incomplete input (982307043.py, line 1)

In [6]:
df=pd.DataFrame({ 
    'name':['A','B','C','D'],
    'age’:[23, 25, 22, 28],
    'score':[88, 92, 79, 95]
})
df

SyntaxError: unterminated string literal (detected at line 3) (1874067157.py, line 3)

In [8]:
df=pd.DataFrame({ 
    'name':['A','B','C','D'],
    'age':[23, 25, 22, 28],
    'score':[88, 92, 79, 95]
})
df

  name  age  score
0    A   23     88
1    B   25     92
2    C   22     79
3    D   28     95

In [9]:
import panda as pd

ModuleNotFoundError: No module named 'panda'

In [10]:
import pandas as pd

In [12]:
teat=pd.DataFrame({
'name':['A','B','C','D'],
'age':[23,24,25,26],
'score':[88,98,90,76]
    
})

In [13]:
teat

  name  age  score
0    A   23     88
1    B   24     98
2    C   25     90
3    D   26     76

In [14]:
teat.head()

  name  age  score
0    A   23     88
1    B   24     98
2    C   25     90
3    D   26     76

In [15]:
teat['name']

0    A
1    B
2    C
3    D
Name: name, dtype: str

In [ ]:
teat