In [1]:
import pandas as pd

In [3]:
import sqlite3

In [4]:
conn=sqlite3.connect('test.db')

In [5]:
head(conn)

NameError: name 'head' is not defined

In [6]:
url='https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [7]:
head(url)

NameError: name 'head' is not defined

In [9]:
df=pd.read_csv(url)

URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1082)>

In [14]:
df=pd.read_csv(url)

In [16]:
df.to_sql('titanic',conn, if_exists='replace',index=False)

891

In [17]:
pd.read_sql('SELECT Pclass, AVG(Age)  AS avg_age, COUNT(*) AS cny FROM titanic GROUP BY Pclass',conn)

   Pclass    avg_age  cny
0       1  38.233441  216
1       2  29.877630  184
2       3  25.140620  491

In [20]:
df.groupby('Pclass')['Age'].agg(['mean','count'])

             mean  count
Pclass
1       38.233441    186
2       29.877630    173
3       25.140620    355

In [21]:
df1=pd.DataFrame({'id':[1,2,3],'name':['A','B','C']})

In [22]:
df2=pd.DataFrame({'id':[1,2,4],'score':[88,92,79]})

In [28]:
df2.to_sql('t2', conn, if_exists='replace', index=False)

3

In [29]:
df1.to_sql('t1', conn, if_exists='replace', index=False)

3

In [30]:
df1.to_sql('t1',conn,if_exists='replace',index=False)

3

In [31]:
#SQL enquiry

In [32]:
pd.read_sql('SELECT * FROM t1 INNER JOIN t2 ON t1.id=t2.id', conn)

   id name  id  score
0   1    A   1     88
1   2    B   2     92

In [34]:
pd.read_sql('SELECT * FROM t1 LEfT JOIN t2 ON t1.id=t2.id', conn)

   id name   id  score
0   1    A  1.0   88.0
1   2    B  2.0   92.0
2   3    C  NaN    NaN

In [35]:
# PANDAS

In [36]:
pd.merge(df1,df2, on='id',how='inner')

   id name  score
0   1    A     88
1   2    B     92

In [37]:
pd.merge(df1,df2,on='id',how='left')

   id name  score
0   1    A   88.0
1   2    B   92.0
2   3    C    NaN

In [38]:
# SQL_CASE WHEN

In [42]:
pd.read_sql('''
SELECT name,
  CASE WHEN score >= 90 THEN 'high'
       WHEN score >= 80 THEN 'mid'
       ELSE 'low' END AS level
FROM t2
''', conn)

DatabaseError: Execution failed on sql '
SELECT name,
  CASE WHEN score >= 90 THEN 'high'
       WHEN score >= 80 THEN 'mid'
       ELSE 'low' END AS level
FROM t2
': no such column: name

In [43]:
df2['level']=pd.cut(df2['score'], bins=[0, 80, 90, 100], labels =['low','mid','high'])