In [1]:
#python

In [3]:
import pandas as pd

In [4]:
import sqlite3

In [5]:
conn=sqlite3.connect('test.db')

In [6]:
url='https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [7]:
df=pd.read_csv(url)

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df1=pd.DataFrame({'id':[1,2,3], 'name': ['A','B','C']})

In [16]:
df2=pd.DataFrame({'id': [1,2,4], 'score': [88, 92, 79]})

In [17]:
pd.merge(df1,df2,on='id', how='inner')

   id  score_x  score_y
0   1       88       88
1   2       92       92
2   4       79       79

In [18]:
pd.merge(df1,df2, on='id',how='left')

   id  score_x  score_y
0   1       88       88
1   2       92       92
2   4       79       79

In [19]:
df.pivot_table(values='Survived', index='Sex',columns='Pclass', aggfunc='mean')

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [24]:
df['Age'].fillna(df['Age'].mean(), inplace=True)   # 用平均年龄填

C:\Users\HW\AppData\Local\Temp\ipykernel_9528\502957613.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)   # 用平均年龄填

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [27]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

C:\Users\HW\AppData\Local\Temp\ipykernel_9528\1698716155.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(), inplace=True)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [29]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

C:\Users\HW\AppData\Local\Temp\ipykernel_9528\3744086084.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [30]:
df.pivot_table(values='Survived', index='Sex', columns='Pclass', aggfunc='mean')

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [31]:
df['AgeGroup']=pd.cut(df['Age'], bins=[0, 18, 35, 60, 100], labels=['Child', 'young','adult','senior'])

In [34]:
df.groupby('AgeGroup')['Survived'].mean()

AgeGroup
Child     0.503597
young     0.382682
adult     0.400000
senior    0.227273
Name: Survived, dtype: float64